# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [2]:
baby_names = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv')
baby_names

         Unnamed: 0       Id     Name  Year Gender State  Count
0             11349    11350     Emma  2004      F    AK     62
1             11350    11351  Madison  2004      F    AK     48
2             11351    11352   Hannah  2004      F    AK     46
3             11352    11353    Grace  2004      F    AK     44
4             11353    11354    Emily  2004      F    AK     41
...             ...      ...      ...   ...    ...   ...    ...
1016390     5647421  5647422     Seth  2014      M    WY      5
1016391     5647422  5647423  Spencer  2014      M    WY      5
1016392     5647423  5647424     Tyce  2014      M    WY      5
1016393     5647424  5647425   Victor  2014      M    WY      5
1016394     5647425  5647426   Waylon  2014      M    WY      5

[1016395 rows x 7 columns]

### Step 4. See the first 10 entries

In [4]:
baby_names.iloc[0:10]

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [5]:
baby_names.drop(columns=["Unnamed: 0", "Id"])

            Name  Year Gender State  Count
0           Emma  2004      F    AK     62
1        Madison  2004      F    AK     48
2         Hannah  2004      F    AK     46
3          Grace  2004      F    AK     44
4          Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
1016390     Seth  2014      M    WY      5
1016391  Spencer  2014      M    WY      5
1016392     Tyce  2014      M    WY      5
1016393   Victor  2014      M    WY      5
1016394   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

### Step 6. What year has the highest number of baby names in the dataset?

In [14]:
baby_names.groupby("Year")["Count"].sum().idxmax()

2007

### Step 7. Is there more male or female names in the dataset?

In [ ]:
baby_names.groupby("Year")["Count"].sum().idxmax()

### Step 8. Group the dataset by name and assign to names

In [15]:
baby_names['Gender'].value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

### Step 9. How many different names exist in the dataset?

In [19]:
baby_names.groupby("Name").max()

         Unnamed: 0       Id  Year Gender State  Count
Name
Aaban       3867935  3867936  2014      M    NY      6
Aadan       5061278  5061279  2014      M    TX      7
Aadarsh     1728030  1728031  2009      M    IL      5
Aaden       5618550  5618551  2014      M    WV    158
Aadhav       709606   709607  2014      M    CA      6
...             ...      ...   ...    ...   ...    ...
Zyra        4936691  4936692  2014      F    TX      8
Zyrah       4933618  4933619  2013      F    TX      6
Zyren       5074229  5074230  2013      M    TX      6
Zyria       4918965  4918966  2014      F    TX      7
Zyriah      4937323  4937324  2014      F    TX     10

[17632 rows x 6 columns]

### Step 10. What is the name with most occurrences?

In [ ]:
baby_names.N.idxmax()

107416

### Step 11. How many different names have the least occurrences?

In [ ]:
baby_names.groupby("Name")["Count"].sum().idxmin()

5

### Step 12. What is the median name occurrence?

In [ ]:
names = baby_names.groupby("Name").sum(numeric_only=True)
names[names.Count == names.Count.median()]

         Unnamed: 0        Id   Year  Count
Name
Aishani     7810519   7810526  14078     49
Alara      18841019  18841027  16079     49
Alysse     22629397  22629405  16057     49
Ameir      21780403  21780411  16086     49
Anely       4349533   4349541  16071     49
...             ...       ...    ...    ...
Sriram      9208196   9208203  14054     49
Trinton    32822294  32822302  16069     49
Vita       10241625  10241632  14075     49
Yoni        6439146   6439154  16060     49
Zuleima     3521366   3521373  14050     49

[66 rows x 4 columns]

### Step 13. What is the standard deviation of names?

In [36]:
names.Count.std()

11006.06946789057

### Step 14. Get a summary with the mean, min, max, std and quartiles.

In [39]:
names.Count.describe()

count     17632.000000
mean       2008.932169
std       11006.069468
min           5.000000
25%          11.000000
50%          49.000000
75%         337.000000
max      242874.000000
Name: Count, dtype: float64